title: "HoX Getting Started"
description: "A getting started guide for the command line and graphical tools provided by the HoX Platform"
url: https://hoxbio.github.io
repository: hoxbio/hoxbio.github.io

markdown: GFM
plugins:
  - jekyll-gfm-admonitions

exclude: 
- "**/*.ts" # Exclude source code files!
- "**/*.js"
- "*.ts" # Also those in the root directory!
- "*.js"
- "*.json" # Don't forget about assets!
- node_modules/ # And large vendored directories
# And these ignore all the artifacts the build produces:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- .gitignore